export const BossDatabase = [
  {
    id: "BOSS-013",
    name: "ราชันมังกรเพลิง",
    mapId: "MAP-013",
    level: 28,
    hp: 28000,
    mp: 448,
    atk: 1120,
    def: 560,
    agi: 48,
    combatStyle: "Fire",
    goldReward: "4000-10000",
    uniqueDrops: ["เพลิงมังกรกระบี่", "ลาวาเกราะ", "มังกรตราประทับ", "เพลิงสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "มังกรเพลิงโบราณที่ตื่นขึ้นจากการหลับใหล ผลิตลาวาเป็นอาหาร"
  },
  {
    id: "BOSS-014",
    name: "ราชินีน้ำแข็ง",
    mapId: "MAP-014",
    level: 29,
    hp: 29000,
    mp: 464,
    atk: 1160,
    def: 580,
    agi: 52,
    combatStyle: "Ice",
    goldReward: "4200-10500",
    uniqueDrops: ["น้ำแข็งราชินีกระบี่", "เหมันต์เกราะ", "หิมะตราประทับ", "น้ำแข็งจี้"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ผู้นำสำนักน้ำแข็งที่ซ่อนตัวใต้ทะเลสาบ วิชาน้ำแข็งขั้นสุดยอด"
  },
  {
    id: "BOSS-015",
    name: "ราชันต้นไม้โบราณ",
    mapId: "MAP-015",
    level: 30,
    hp: 30000,
    mp: 480,
    atk: 1200,
    def: 600,
    agi: 45,
    combatStyle: "Melee",
    goldReward: "4400-11000",
    uniqueDrops: ["ต้นไม้ทวน", "พฤกษาเกราะ", "โบราณตราประทับ", "รากไม้กำไล"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ต้นไม้ยักษ์ที่มีจิตวิญญาณและโจมตีทุกคนที่เข้าใกล้ รากไม้ทะลวง"
  },
  {
    id: "BOSS-016",
    name: "ราชันสายฟ้า",
    mapId: "MAP-016",
    level: 31,
    hp: 31000,
    mp: 496,
    atk: 1240,
    def: 620,
    agi: 58,
    combatStyle: "Lightning",
    goldReward: "4600-11500",
    uniqueDrops: ["สายฟ้าราชันกระบี่", "อัสนีเกราะ", "ฟ้าผ่าตราประทับ", "สายฟ้าแหวน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "สัตว์อสูรสายฟ้าโบราณที่ครองหุบเขา โจมตีรวดเร็วดั่งฟ้าผ่า"
  },
  {
    id: "BOSS-017",
    name: "จอมกระบี่ผีดิบ",
    mapId: "MAP-017",
    level: 32,
    hp: 32000,
    mp: 512,
    atk: 1280,
    def: 640,
    agi: 55,
    combatStyle: "Melee",
    goldReward: "4800-12000",
    uniqueDrops: ["ผีดิบกระบี่", "สุสานเกราะ", "ตำนานตราประทับ", "วิญญาณสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "อดีตจอมยุทธ์ระดับตำนานที่กลายเป็นผีดิบเฝ้าสุสาน กระบี่ผีดิบไร้พ่าย"
  },
  {
    id: "BOSS-018",
    name: "ราชันมารโลหิต",
    mapId: "MAP-018",
    level: 33,
    hp: 33000,
    mp: 528,
    atk: 1320,
    def: 660,
    agi: 50,
    combatStyle: "Dark",
    goldReward: "5000-12500",
    uniqueDrops: ["โลหิตมารดาบ", "ตำหนักเกราะ", "มารตราประทับ", "เลือดกำไล"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ผู้นำลัทธิมารที่ฝึกวิชาดูดเลือดจนหยั่งถึงขั้นเซียน ดาบมารโลหิต"
  },
  {
    id: "BOSS-019",
    name: "ปราชญ์ดอกท้อ",
    mapId: "MAP-019",
    level: 38,
    hp: 38000,
    mp: 608,
    atk: 1520,
    def: 760,
    agi: 62,
    combatStyle: "Magic",
    goldReward: "6000-15000",
    uniqueDrops: ["ดอกท้อพิณ", "ท้อเกราะ", "ปราชญ์ตราประทับ", "ท้อจี้"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ปราชญ์ผู้ยิ่งใหญ่ที่ครองเกาะมานับร้อยปี พิณดอกท้อสะกดจิต"
  },
  {
    id: "BOSS-020",
    name: "ราชันมังกรซ่อน",
    mapId: "MAP-020",
    level: 39,
    hp: 39000,
    mp: 624,
    atk: 1560,
    def: 780,
    agi: 58,
    combatStyle: "Melee",
    goldReward: "6200-15500",
    uniqueDrops: ["ซ่อนมังกรดาบ", "ถ้ำเกราะ", "มังกรตราประทับ", "เกล็ดสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "มังกรโบราณที่หลับใหลอยู่ในถ้ำลึก ดาบมังกรซ่อนสะท้านพิภพ"
  },
  {
    id: "BOSS-021",
    name: "เจ้าสำนักพิษหมื่นพิษ",
    mapId: "MAP-021",
    level: 40,
    hp: 40000,
    mp: 640,
    atk: 1600,
    def: 800,
    agi: 65,
    combatStyle: "Poison",
    goldReward: "6400-16000",
    uniqueDrops: ["หมื่นพิษเข็ม", "พิษเกราะ", "สำนักตราประทับ", "พิษแหวน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสำนักพิษที่ฝึกวิชาพิษจนหยั่งถึงขั้นเซียน เข็มหมื่นพิษร้ายกาจ"
  },
  {
    id: "BOSS-022",
    name: "เจ้าสำนักเอ๋อเหมย",
    mapId: "MAP-022",
    level: 41,
    hp: 41000,
    mp: 656,
    atk: 1640,
    def: 820,
    agi: 68,
    combatStyle: "Melee",
    goldReward: "6600-16500",
    uniqueDrops: ["เอ๋อเหมยกระบี่", "ภูเขาเกราะ", "สำนักตราประทับ", "หยกสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสำนักที่ฝึกวิชากระบี่และรักษาจนหยั่งถึงขั้นเซียน กระบี่เอ๋อเหมย"
  },
  {
    id: "BOSS-023",
    name: "เจ้าสำนักไร้ใจ",
    mapId: "MAP-023",
    level: 42,
    hp: 42000,
    mp: 672,
    atk: 1680,
    def: 840,
    agi: 70,
    combatStyle: "Dark",
    goldReward: "6800-17000",
    uniqueDrops: ["ไร้ใจดาบ", "ความว่างเปล่าเกราะ", "สำนักตราประทับ", "จิตแหวน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสำนักที่ฝึกวิชาควบคุมจิตใจจนหยั่งถึงขั้นเซียน ดาบไร้ใจ"
  },
  {
    id: "BOSS-024",
    name: "ราชินีน้ำแข็งนิรันดร์",
    mapId: "MAP-024",
    level: 48,
    hp: 48000,
    mp: 768,
    atk: 1920,
    def: 960,
    agi: 72,
    combatStyle: "Ice",
    goldReward: "8000-20000",
    uniqueDrops: ["นิรันดร์กระบี่", "น้ำแข็งเกราะ", "ราชินีตราประทับ", "หิมะกำไล"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชินีแห่งดินแดนน้ำแข็งที่ครองมานับพันปี กระบี่นิรันดร์แช่แข็งทุกสิ่ง"
  },
  {
    id: "BOSS-025",
    name: "ราชันปราสาททมิฬ",
    mapId: "MAP-025",
    level: 49,
    hp: 49000,
    mp: 784,
    atk: 1960,
    def: 980,
    agi: 65,
    combatStyle: "Dark",
    goldReward: "8200-20500",
    uniqueDrops: ["ทมิฬดาบ", "ปราสาทเกราะ", "ราชันตราประทับ", "คำสาปสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ถูกสาปให้เป็นอมตะเฝ้าปราสาท ดาบทมิฬผสมพลังสาป"
  },
  {
    id: "BOSS-026",
    name: "จักรพรรดิผีดิบ",
    mapId: "MAP-026",
    level: 50,
    hp: 50000,
    mp: 800,
    atk: 2000,
    def: 1000,
    agi: 68,
    combatStyle: "Dark",
    goldReward: "8400-21000",
    uniqueDrops: ["จักรพรรดิหอก", "สุสานเกราะ", "จักรพรรดิตราประทับ", "อัญมณีสร้อยคอ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จักรพรรดิโบราณที่ถูกสาปให้เป็นผีดิบเฝ้าสุสาน หอกจักรพรรดิไร้พ่าย"
  },
  {
    id: "BOSS-027",
    name: "ราชันมังกรโบราณ",
    mapId: "MAP-027",
    level: 51,
    hp: 51000,
    mp: 816,
    atk: 2040,
    def: 1020,
    agi: 75,
    combatStyle: "Melee",
    goldReward: "8600-21500",
    uniqueDrops: ["โบราณมังกรกระบี่", "หุบเขาเกราะ", "ราชันตราประทับ", "เกล็ดมังกรแหวน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "มังกรโบราณที่ครองหุบเขามานับพันปี กระบี่มังกรโบราณสะท้านพิภพ"
  },
  {
    id: "BOSS-028",
    name: "ราชันวิญญาณ",
    mapId: "MAP-028",
    level: 52,
    hp: 52000,
    mp: 832,
    atk: 2080,
    def: 1040,
    agi: 78,
    combatStyle: "Dark",
    goldReward: "8800-22000",
    uniqueDrops: ["วิญญาณพัด", "ดินแดนเกราะ", "ราชันตราประทับ", "ผีดิบจี้"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันวิญญาณที่ครองดินแดนมานับพันปี พัดวิญญาณดูดกลืนชีวิต"
  },
  {
    id: "BOSS-029",
    name: "เจ้าสำนักเซียนลับ",
    mapId: "MAP-029",
    level: 53,
    hp: 53000,
    mp: 848,
    atk: 2120,
    def: 1060,
    agi: 80,
    combatStyle: "Magic",
    goldReward: "9000-22500",
    uniqueDrops: ["เซียนลับกระบี่", "ภูเขาหิมะเกราะ", "เจ้าสำนักตราประทับ", "เซียนหยกพก"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสำนักที่ฝึกวิชาจนหยั่งถึงขั้นเซียน กระบี่เซียนลับผสมพลังเวทย์"
  },
  {
    id: "BOSS-030",
    name: "ราชันปีศาจ",
    mapId: "MAP-030",
    level: 54,
    hp: 54000,
    mp: 864,
    atk: 2160,
    def: 1080,
    agi: 74,
    combatStyle: "Dark",
    goldReward: "9200-23000",
    uniqueDrops: ["ปีศาจดาบ", "มารเกราะ", "ราชันตราประทับ", "ตรามารประทับ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันปีศาจที่ครองดินแดนมานับพันปี ดาบปีศาจเต็มไปด้วยพลังมาร"
  },
  {
    id: "BOSS-031",
    name: "จอมเซียนดนตรี",
    mapId: "MAP-031",
    level: 58,
    hp: 58000,
    mp: 928,
    atk: 2320,
    def: 1160,
    agi: 85,
    combatStyle: "Magic",
    goldReward: "10000-25000",
    uniqueDrops: ["พิณเสียงสวรรค์", "ขลุ่ยเซียน", "ชุดคลุมจอมเซียน", "แหวนเสียงวิญญาณ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จอมเซียนดนตรีที่ครองดินแดนเสียงสวรรค์ พลังเสียงสะท้านทุกมิติ"
  },
  {
    id: "BOSS-032",
    name: "ราชันดาวตก",
    mapId: "MAP-032",
    level: 59,
    hp: 59000,
    mp: 944,
    atk: 2360,
    def: 1180,
    agi: 90,
    combatStyle: "Magic",
    goldReward: "10200-25500",
    uniqueDrops: ["ดาวตกดาบ", "คริสตัลดาวตก", "เกราะดาว", "แหวนดาวตก"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่เกิดจากแสงดาวรวมตัวกัน พลังดาวตกทำลายล้างทุกสิ่งที่ขวางหน้า"
  },
  {
    id: "BOSS-033",
    name: "จอมกระบี่สวรรค์",
    mapId: "MAP-033",
    level: 60,
    hp: 60000,
    mp: 960,
    atk: 2400,
    def: 1200,
    agi: 95,
    combatStyle: "Melee",
    goldReward: "10400-26000",
    uniqueDrops: ["กระบี่สวรรค์", "เกราะสวรรค์", "ตราประทับสวรรค์", "สร้อยคอจอมกระบี่"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จอมกระบี่ที่ครองหุบเขาดาบสวรรค์ กระบี่ไร้เทียมทาน"
  },
  {
    id: "BOSS-034",
    name: "ราชันเวลา",
    mapId: "MAP-034",
    level: 61,
    hp: 61000,
    mp: 976,
    atk: 2440,
    def: 1220,
    agi: 88,
    combatStyle: "Magic",
    goldReward: "10600-26500",
    uniqueDrops: ["นาฬิกาเวลา", "ชุดคลุมเวลา", "แหวนเวลา", "ตราประทับเวลา"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ครองปราสาทเวลา หยุดเวลาได้ตามอำเภอใจ"
  },
  {
    id: "BOSS-035",
    name: "เจ้าสวนเซียน",
    mapId: "MAP-035",
    level: 62,
    hp: 62000,
    mp: 992,
    atk: 2480,
    def: 1240,
    agi: 82,
    combatStyle: "Support",
    goldReward: "10800-27000",
    uniqueDrops: ["น้ำพุอมฤต", "ดอกไม้เซียน", "เสื้อคลุมสวนเซียน", "แหวนอมฤต"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสวนเซียนที่ปลูกสมุนไพรวิเศษ พลังฟื้นฟูและทำลายพร้อมกัน"
  },
  {
    id: "BOSS-036",
    name: "ราชันเทพมาร",
    mapId: "MAP-036",
    level: 68,
    hp: 68000,
    mp: 1088,
    atk: 2720,
    def: 1360,
    agi: 100,
    combatStyle: "Dark",
    goldReward: "12000-30000",
    uniqueDrops: ["ดาบเทพมาร", "เกราะเทพมาร", "ตราประทับเทพมาร", "สร้อยคอเทพมาร"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ครองวังเทพมาร พลังทั้งศักดิ์สิทธิ์และมารร้าย"
  },
  {
    id: "BOSS-037",
    name: "ราชันวิญญาณนิรันดร์",
    mapId: "MAP-037",
    level: 69,
    hp: 69000,
    mp: 1104,
    atk: 2760,
    def: 1380,
    agi: 105,
    combatStyle: "Dark",
    goldReward: "12200-30500",
    uniqueDrops: ["พัดวิญญาณ", "เสื้อคลุมวิญญาณ", "ตราประทับวิญญาณ", "จี้วิญญาณ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันวิญญาณที่ไม่มีวันตาย ดูดกลืนชีวิตทุกสิ่งที่เคลื่อนไหว"
  },
  {
    id: "BOSS-038",
    name: "เทพเจ้าผีดิบ",
    mapId: "MAP-038",
    level: 70,
    hp: 70000,
    mp: 1120,
    atk: 2800,
    def: 1400,
    agi: 95,
    combatStyle: "Dark",
    goldReward: "12400-31000",
    uniqueDrops: ["หอกเทพผีดิบ", "เกราะสุสานเทพ", "ตราจักรพรรดิ", "อัญมณีเทพเจ้า"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เทพเจ้าโบราณที่ถูกสาปให้เป็นผีดิบเฝ้าสุสาน"
  },
  {
    id: "BOSS-039",
    name: "เจ้าเกาะเซียน",
    mapId: "MAP-039",
    level: 71,
    hp: 71000,
    mp: 1136,
    atk: 2840,
    def: 1420,
    agi: 100,
    combatStyle: "Magic",
    goldReward: "12600-31500",
    uniqueDrops: ["กระบี่เซียน", "เสื้อคลุมเซียน", "ตราเจ้าสำนัก", "หยกเซียน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าเกาะเซียนลอยฟ้า ฝึกวิชาจนบรรลุขั้นเทพ"
  },
  {
    id: "BOSS-040",
    name: "ราชันมิติ",
    mapId: "MAP-040",
    level: 72,
    hp: 72000,
    mp: 1152,
    atk: 2880,
    def: 1440,
    agi: 110,
    combatStyle: "Magic",
    goldReward: "12800-32000",
    uniqueDrops: ["ดาบมิติ", "เสื้อคลุมมิติ", "แหวนมิติ", "ตราประทับมิติ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ครองหุบเขามิติแตก ควบคุมมิติคู่ขนานได้"
  },
  {
    id: "BOSS-041",
    name: "จักรพรรดิเทพมาร",
    mapId: "MAP-041",
    level: 73,
    hp: 73000,
    mp: 1168,
    atk: 2920,
    def: 1460,
    agi: 105,
    combatStyle: "Dark",
    goldReward: "13000-32500",
    uniqueDrops: ["มงกุฎเทพมาร", "เกราะจักรพรรดิ", "ตราประทับอาณาจักร", "หยกเทพมาร"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จักรพรรดิที่ครองอาณาจักรเทพมารโบราณ พลังไร้ขีดจำกัด"
  },
  {
    id: "BOSS-042",
    name: "เทพเจ้าสวรรค์ชั้นเก้า",
    mapId: "MAP-042",
    level: 78,
    hp: 78000,
    mp: 1248,
    atk: 3120,
    def: 1560,
    agi: 115,
    combatStyle: "Holy",
    goldReward: "15000-37500",
    uniqueDrops: ["กระบี่สวรรค์", "เกราะเทพ", "มงกุฎสวรรค์", "ตราประทับเทพเจ้า"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เทพเจ้าผู้ครองสวรรค์ชั้นเก้า แสงศักดิ์สิทธิ์แผดเผามารทั้งปวง"
  },
  {
    id: "BOSS-043",
    name: "ราชันเซียน",
    mapId: "MAP-043",
    level: 79,
    hp: 79000,
    mp: 1264,
    atk: 3160,
    def: 1580,
    agi: 110,
    combatStyle: "Magic",
    goldReward: "15200-38000",
    uniqueDrops: ["พิณเซียน", "ชุดเซียน", "ตราราชัน", "จี้เซียน"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันเซียนผู้ครองโลกเซียน เวทมนตร์ไร้ขีดจำกัด"
  },
  {
    id: "BOSS-044",
    name: "เทพเจ้าโลกเทพ",
    mapId: "MAP-044",
    level: 80,
    hp: 80000,
    mp: 1280,
    atk: 3200,
    def: 1600,
    agi: 120,
    combatStyle: "Holy",
    goldReward: "15400-38500",
    uniqueDrops: ["ดาบเทพ", "เกราะโลกเทพ", "มงกุฎเทพ", "ตราเทพเจ้า"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เทพเจ้าผู้ครองโลกเทพ พลังศักดิ์สิทธิ์ล้างบาปทุกสิ่ง"
  },
  {
    id: "BOSS-045",
    name: "ราชันบรรพกาล",
    mapId: "MAP-045",
    level: 88,
    hp: 88000,
    mp: 1408,
    atk: 3520,
    def: 1760,
    agi: 115,
    combatStyle: "Dark",
    goldReward: "18000-45000",
    uniqueDrops: ["ดาบบรรพกาล", "เกราะบรรพกาล", "ตราราชัน", "สร้อยคอบรรพกาล"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ครองดินแดนบรรพกาล พลังดึกดำบรรพ์ทำลายล้าง"
  },
  {
    id: "BOSS-046",
    name: "ผู้พิทักษ์เขตต้องห้าม",
    mapId: "MAP-046",
    level: 89,
    hp: 89000,
    mp: 1424,
    atk: 3560,
    def: 1780,
    agi: 110,
    combatStyle: "Melee",
    goldReward: "18200-45500",
    uniqueDrops: ["หอกต้องห้าม", "เกราะต้องห้าม", "ตราพิทักษ์", "แหวนต้องห้าม"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าเขตต้องห้าม ไม่มีใครผ่านไปได้"
  },
  {
    id: "BOSS-047",
    name: "จักรพรรดิเทพผีดิบ",
    mapId: "MAP-047",
    level: 90,
    hp: 90000,
    mp: 1440,
    atk: 3600,
    def: 1800,
    agi: 120,
    combatStyle: "Dark",
    goldReward: "18400-46000",
    uniqueDrops: ["กระบี่จักรพรรดิ", "เกราะสุสาน", "มงกุฎผีดิบ", "ตราจักรพรรดิ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จักรพรรดิเทพที่ถูกสาปให้เป็นผีดิบเฝ้าสุสานชั่วนิรันดร์"
  },
  {
    id: "BOSS-048",
    name: "ราชันจักรวาล",
    mapId: "MAP-048",
    level: 91,
    hp: 91000,
    mp: 1456,
    atk: 3640,
    def: 1820,
    agi: 125,
    combatStyle: "Magic",
    goldReward: "18600-46500",
    uniqueDrops: ["ดาบจักรวาล", "เสื้อคลุมจักรวาล", "แหวนดารา", "ตราจักรวาล"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ราชันที่ครองหุบเขาจักรวาล ควบคุมดวงดาวและกาแล็กซี"
  },
  {
    id: "BOSS-049",
    name: "เจ้าสำนักมหาเทพ",
    mapId: "MAP-049",
    level: 91,
    hp: 91000,
    mp: 1456,
    atk: 3640,
    def: 1820,
    agi: 130,
    combatStyle: "Melee",
    goldReward: "18800-47000",
    uniqueDrops: ["กระบี่มหาเทพ", "เกราะมหาเทพ", "ตราเจ้าสำนัก", "หยกมหาเทพ"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เจ้าสำนักมหาเทพ ผู้ฝึกวิชาสูงสุดแห่งสากลจักรวาล"
  },
  {
    id: "BOSS-050",
    name: "ผู้พิทักษ์ประตูสวรรค์",
    mapId: "MAP-050",
    level: 90,
    hp: 90000,
    mp: 1440,
    atk: 3600,
    def: 1800,
    agi: 125,
    combatStyle: "Holy",
    goldReward: "25000-62500",
    uniqueDrops: ["ดาบประตูสวรรค์", "เกราะผู้พิทักษ์", "ตราประตูสวรรค์", "แหวนสวรรค์"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "ผู้พิทักษ์ประตูสวรรค์ ผู้คัดกรองผู้ที่คู่ควรให้ผ่านเข้าสู่สวรรค์ชั้นสูงสุด"
  },
  {
    id: "BOSS-051",
    name: "เทพเจ้าสูงสุด",
    mapId: "MAP-051",
    level: 90,
    hp: 90000,
    mp: 1440,
    atk: 3600,
    def: 1800,
    agi: 130,
    combatStyle: "Holy",
    goldReward: "25500-63750",
    uniqueDrops: ["กระบี่เทพสูงสุด", "มงกุฎสวรรค์", "ตราเทพสูงสุด", "จี้แสงศักดิ์สิทธิ์"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "เทพเจ้าสูงสุดผู้ครองสวรรค์ชั้นสูงสุด แสงศักดิ์สิทธิ์ครอบคลุมทุกสิ่ง"
  },
  {
    id: "BOSS-052",
    name: "จักรพรรดิแห่งสวรรค์",
    mapId: "MAP-052",
    level: 90,
    hp: 90000,
    mp: 1440,
    atk: 3600,
    def: 1800,
    agi: 140,
    combatStyle: "Holy",
    goldReward: "30000-75000",
    uniqueDrops: ["จักรพรรดิกระบี่", "มงกุฎจักรพรรดิ", "ตราแห่งสวรรค์", "หยกสร้างโลก"],
    reset: "1 ครั้ง/สัปดาห์ (Weekly Reset)",
    immunity: "KILL_CHANCE (ไม่ตายทันที)",
    specialPhase: "Phase 2 เมื่อ HP < 50%",
    description: "จักรพรรดิผู้สร้างจักรวาล บอสสุดท้ายแห่งเกม ผู้มีพลังไร้ขีดจำกัด"
  }
];