const miniBossDatabase = [
  {
    bossId: "MINI-007",
    name: "หมัดเหล็กหัวซาน",
    mapId: "MAP-007",
    level: 16,
    hp: 6400,
    mp: 192,
    atk: 384,
    def: 192,
    agi: 35,
    style: "Melee",
    goldReward: "800-1280",
    uniqueDrops: ["เหล็กไหลกระบอง", "สำริดเสื้อเกราะ", "หยกพก"],
    description: "อดีตศิษย์เอกสำนักหัวซานที่ถูกไล่ออก ฝีมือหมัดเหล็กไร้เทียมทาน",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-008",
    name: "เต๋าจื่อลับ",
    mapId: "MAP-008",
    level: 17,
    hp: 6800,
    mp: 204,
    atk: 408,
    def: 204,
    agi: 32,
    style: "Dark",
    goldReward: "880-1360",
    uniqueDrops: ["เงาพัด", "มารจีวร", "ยันต์คุ้มภัย"],
    description: "นักพรตที่หลงผิดในวิชามืด ใช้พลังเต๋าจื่อในการทำลายล้าง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-009",
    name: "แม่มดป่าดงดิบ",
    mapId: "MAP-009",
    level: 18,
    hp: 7200,
    mp: 216,
    atk: 432,
    def: 216,
    agi: 38,
    style: "Poison",
    goldReward: "960-1440",
    uniqueDrops: ["พิษเข็ม", "พฤกษาเสื้อคลุม", "ถุงหอม"],
    description: "หญิงชราที่ฝึกวิชาพิษในป่าลึก สร้างพิษจากพืชป่าได้ทุกชนิด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-010",
    name: "ราชันแมงป่องดำ",
    mapId: "MAP-010",
    level: 19,
    hp: 7600,
    mp: 228,
    atk: 456,
    def: 228,
    agi: 40,
    style: "Poison",
    goldReward: "1040-1520",
    uniqueDrops: ["แมงป่องพลอง", "ทรายเกราะ", "กำไลข้อเท้า"],
    description: "แมงป่องยักษ์ที่กลายพันธุ์จากพลังปราณโบราณ มีพิษร้ายแรง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-011",
    name: "เจ้าสำนักพิษคนก่อน",
    mapId: "MAP-011",
    level: 20,
    hp: 8000,
    mp: 240,
    atk: 480,
    def: 240,
    agi: 36,
    style: "Poison",
    goldReward: "1120-1600",
    uniqueDrops: ["พิษกระบี่", "หมอกพิษเสื้อคลุม", "พิษแหวน"],
    description: "อดีตเจ้าสำนักที่ถูกไล่ออกเพราะฝึกวิชาพิษต้องห้าม พิษร้ายกาจ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-012",
    name: "พระลูกวัดหลงผิด",
    mapId: "MAP-012",
    level: 21,
    hp: 8400,
    mp: 252,
    atk: 504,
    def: 252,
    agi: 30,
    style: "Dark",
    goldReward: "1200-1760",
    uniqueDrops: ["มารดาบ", "จีวรมืด", "ลูกปะคำ"],
    description: "อดีตพระลูกวัดที่หลงผิดในวิชามาร กำลังภายนอกผสมพลังมืด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-013",
    name: "หัวหน้านักขุดแร่",
    mapId: "MAP-013",
    level: 27,
    hp: 10800,
    mp: 324,
    atk: 648,
    def: 324,
    agi: 42,
    style: "Melee",
    goldReward: "1350-2160",
    uniqueDrops: ["ลาวาพลอง", "แร่ธาตุเกราะ", "แหวนทองเหลือง"],
    description: "นักขุดแร่ที่ได้รับพลังจากแร่ธาตุโบราณ ร่างกายแข็งแกร่งดั่งหิน",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-014",
    name: "ศิษย์เอกสำนักน้ำแข็ง",
    mapId: "MAP-014",
    level: 28,
    hp: 11200,
    mp: 336,
    atk: 672,
    def: 336,
    agi: 45,
    style: "Ice",
    goldReward: "1400-2240",
    uniqueDrops: ["น้ำแข็งกระบี่", "เหมันต์เสื้อคลุม", "หิมะจี้"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องทะเลสาบ วิชาน้ำแข็งลึกลับ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-015",
    name: "นักล่าสัตว์อสูร",
    mapId: "MAP-015",
    level: 29,
    hp: 11600,
    mp: 348,
    atk: 696,
    def: 348,
    agi: 48,
    style: "Melee",
    goldReward: "1450-2320",
    uniqueDrops: ["อสูรหอก", "ป่าเสื้อเกราะ", "เขี้ยวพยัคฆ์สร้อยคอ"],
    description: "นักล่าที่ถูกสัตว์อสูรครอบงำจิตใจ ทั้งแข็งแกร่งและบ้าคลั่ง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-016",
    name: "หัวหน้านักขุดแร่สายฟ้า",
    mapId: "MAP-016",
    level: 30,
    hp: 12000,
    mp: 360,
    atk: 720,
    def: 360,
    agi: 50,
    style: "Lightning",
    goldReward: "1500-2400",
    uniqueDrops: ["สายฟ้าทวน", "อัสนีเกราะ", "ฟ้าแลบแหวน"],
    description: "นักขุดแร่ที่ได้รับพลังสายฟ้า โจมตีรวดเร็วดั่งฟ้าแลบ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-017",
    name: "นักล่ากระบี่ตำนาน",
    mapId: "MAP-017",
    level: 31,
    hp: 12400,
    mp: 372,
    atk: 744,
    def: 372,
    agi: 52,
    style: "Melee",
    goldReward: "1550-2480",
    uniqueDrops: ["ตำนานกระบี่", "สุสานเสื้อคลุม", "กระบี่ต่างหู"],
    description: "นักล่าที่ตามหากระบี่ในตำนาน ฝีมือกระบี่เลื่องชื่อ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-018",
    name: "ผู้พิทักษ์ตำหนักมาร",
    mapId: "MAP-018",
    level: 32,
    hp: 12800,
    mp: 384,
    atk: 768,
    def: 384,
    agi: 46,
    style: "Dark",
    goldReward: "1600-2560",
    uniqueDrops: ["โลหิตดาบ", "มารเกราะ", "เลือดกำไล"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะเฝ้าตำหนัก ดูดเลือดเป็นอาหาร",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-019",
    name: "หัวหน้าโจรทะเล",
    mapId: "MAP-019",
    level: 37,
    hp: 14800,
    mp: 444,
    atk: 888,
    def: 444,
    agi: 55,
    style: "Melee",
    goldReward: "1850-2960",
    uniqueDrops: ["ทะเลดาบ", "คลื่นเสื้อเกราะ", "มุกสร้อยคอ"],
    description: "โจรทะเลที่ยึดครองชายฝั่งเกาะ โจรสลัดผู้ไร้ปราณี",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-020",
    name: "หัวหน้านักขุดแร่ถ้ำ",
    mapId: "MAP-020",
    level: 38,
    hp: 15200,
    mp: 456,
    atk: 912,
    def: 456,
    agi: 48,
    style: "Melee",
    goldReward: "1900-3040",
    uniqueDrops: ["มังกรขวาน", "ถ้ำเกราะ", "แร่ธาตุกำไล"],
    description: "นักขุดแร่ที่ได้รับพลังจากแร่มังกร ร่างกายแข็งแกร่งดั่งเกล็ดมังกร",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-021",
    name: "ผู้พิทักษ์หุบเหวพิษ",
    mapId: "MAP-021",
    level: 39,
    hp: 15600,
    mp: 468,
    atk: 936,
    def: 468,
    agi: 58,
    style: "Poison",
    goldReward: "1950-3120",
    uniqueDrops: ["หมื่นพิษเข็ม", "พิษเสื้อคลุม", "พิษแหวน"],
    description: "ผู้พิทักษ์ที่ถูกพิษเปลี่ยนเป็นอสูร ร่างกายเต็มไปด้วยพิษร้าย",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-022",
    name: "ศิษย์เอกสำนักเอ๋อเหมยหลงผิด",
    mapId: "MAP-022",
    level: 40,
    hp: 16000,
    mp: 480,
    atk: 960,
    def: 480,
    agi: 60,
    style: "Melee",
    goldReward: "2000-3200",
    uniqueDrops: ["เอ๋อเหมยกระบี่", "ภูเขาเสื้อคลุม", "หยกจี้"],
    description: "ศิษย์เอกที่หลงผิดในวิชามาร กระบี่เอ๋อเหมยผสมพลังมืด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-023",
    name: "ผู้พิทักษ์หุบเขาไร้ใจ",
    mapId: "MAP-023",
    level: 41,
    hp: 16400,
    mp: 492,
    atk: 984,
    def: 492,
    agi: 62,
    style: "Dark",
    goldReward: "2050-3280",
    uniqueDrops: ["ไร้ใจดาบ", "ความว่างเปล่าเสื้อคลุม", "จิตแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้ไร้ใจ โจมตีโดยไม่มีความรู้สึกใดๆ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-024",
    name: "ศิษย์เอกสำนักน้ำแข็ง",
    mapId: "MAP-024",
    level: 47,
    hp: 18800,
    mp: 564,
    atk: 1128,
    def: 564,
    agi: 65,
    style: "Ice",
    goldReward: "2350-3760",
    uniqueDrops: ["นิรันดร์กระบี่", "น้ำแข็งเกราะ", "หิมะกำไล"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องดินแดน วิชาน้ำแข็งขั้นสูงสุด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-025",
    name: "ผู้พิทักษ์ปราสาท",
    mapId: "MAP-025",
    level: 48,
    hp: 19200,
    mp: 576,
    atk: 1152,
    def: 576,
    agi: 58,
    style: "Dark",
    goldReward: "2400-3840",
    uniqueDrops: ["ทมิฬดาบ", "ปราสาทเกราะ", "คำสาปตราประทับ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ ดาบทมิฬผสมพลังสาป",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-026",
    name: "ผู้พิทักษ์สุสาน",
    mapId: "MAP-026",
    level: 49,
    hp: 19600,
    mp: 588,
    atk: 1176,
    def: 588,
    agi: 60,
    style: "Dark",
    goldReward: "2450-3920",
    uniqueDrops: ["จักรพรรดิหอก", "สุสานเกราะ", "อัญมณีสร้อยคอ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะเฝ้าสุสาน หอกจักรพรรดิโบราณ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-027",
    name: "ศิษย์เอกสำนักมังกร",
    mapId: "MAP-027",
    level: 50,
    hp: 20000,
    mp: 600,
    atk: 1200,
    def: 600,
    agi: 68,
    style: "Melee",
    goldReward: "2500-4000",
    uniqueDrops: ["มังกรกระบี่", "หุบเขาเกราะ", "เกล็ดมังกรแหวน"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องหุบเขา กระบี่มังกรสะท้านพิภพ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-028",
    name: "ผู้พิทักษ์ดินแดนวิญญาณ",
    mapId: "MAP-028",
    level: 51,
    hp: 20400,
    mp: 612,
    atk: 1224,
    def: 612,
    agi: 70,
    style: "Dark",
    goldReward: "2550-4080",
    uniqueDrops: ["วิญญาณพัด", "ดินแดนเสื้อคลุม", "ผีดิบจี้"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ พัดวิญญาณดูดกลืนชีวิต",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-029",
    name: "ศิษย์เอกสำนักเซียนลับ",
    mapId: "MAP-029",
    level: 52,
    hp: 20800,
    mp: 624,
    atk: 1248,
    def: 624,
    agi: 72,
    style: "Magic",
    goldReward: "2600-4160",
    uniqueDrops: ["เซียนกระบี่", "ภูเขาหิมะเสื้อคลุม", "เซียนหยกพก"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องสำนัก กระบี่เซียนผสมพลังเวทย์",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-030",
    name: "ผู้พิทักษ์ดินแดนปีศาจ",
    mapId: "MAP-030",
    level: 53,
    hp: 21200,
    mp: 636,
    atk: 1272,
    def: 636,
    agi: 66,
    style: "Dark",
    goldReward: "2650-4240",
    uniqueDrops: ["ปีศาจดาบ", "มารเกราะ", "ตรามารประทับ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ ดาบปีศาจเต็มไปด้วยพลังมาร",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-031",
    name: "ศิษย์เอกสำนักเซียนดนตรี",
    mapId: "MAP-031",
    level: 57,
    hp: 22800,
    mp: 684,
    atk: 1368,
    def: 684,
    agi: 75,
    style: "Magic",
    goldReward: "2700-4320",
    uniqueDrops: ["เสียงสวรรค์พิณ", "เซียนดนตรีเสื้อคลุม", "เสียงเพลงแหวน"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องดินแดน เสียงพิณทำลายล้างจิตใจ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-032",
    name: "หัวหน้าโจรดาว",
    mapId: "MAP-032",
    level: 58,
    hp: 23200,
    mp: 696,
    atk: 1392,
    def: 696,
    agi: 78,
    style: "Magic",
    goldReward: "2750-4400",
    uniqueDrops: ["ดาวตกดาบ", "ทะเลดาวเสื้อเกราะ", "แสงดาวสร้อยคอ"],
    description: "โจรที่ได้รับพลังจากแร่ดาว โจมตีรวดเร็วดั่งดาวตก",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-033",
    name: "ศิษย์เอกสำนักกระบี่ลับ",
    mapId: "MAP-033",
    level: 59,
    hp: 23600,
    mp: 708,
    atk: 1416,
    def: 708,
    agi: 80,
    style: "Melee",
    goldReward: "2800-4480",
    uniqueDrops: ["ดาบสวรรค์กระบี่", "หุบเขาดาบเสื้อคลุม", "วิญญาณดาบจี้"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องหุบเขา กระบี่สวรรค์สะท้านฟ้า",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-034",
    name: "ผู้พิทักษ์ปราสาทเวลา",
    mapId: "MAP-034",
    level: 60,
    hp: 24000,
    mp: 720,
    atk: 1440,
    def: 720,
    agi: 72,
    style: "Magic",
    goldReward: "2850-4560",
    uniqueDrops: ["เวลาทวน", "ปราสาทเวลาเกราะ", "นาฬิกาแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ ควบคุมเวลาได้เล็กน้อย",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-035",
    name: "ผู้พิทักษ์สวนเซียน",
    mapId: "MAP-035",
    level: 61,
    hp: 24400,
    mp: 732,
    atk: 1464,
    def: 732,
    agi: 70,
    style: "Magic",
    goldReward: "2900-4640",
    uniqueDrops: ["สวนเซียนกระบี่", "อมฤต์เสื้อคลุม", "น้ำพุแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ ใช้น้ำอมฤต์ฟื้นพลัง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-036",
    name: "ผู้พิทักษ์วังเทพมาร",
    mapId: "MAP-036",
    level: 67,
    hp: 26800,
    mp: 804,
    atk: 1608,
    def: 804,
    agi: 82,
    style: "Dark",
    goldReward: "3100-4960",
    uniqueDrops: ["เทพมารขวาน", "วังเทพมารเกราะ", "เทพมารตราประทับ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ พลังเทพและมารผสานกัน",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-037",
    name: "ผู้พิทักษ์ดินแดนวิญญาณ",
    mapId: "MAP-037",
    level: 68,
    hp: 27200,
    mp: 816,
    atk: 1632,
    def: 816,
    agi: 85,
    style: "Dark",
    goldReward: "3150-5040",
    uniqueDrops: ["วิญญาณนิรันดร์พัด", "ดินแดนวิญญาณเสื้อคลุม", "วิญญาณจี้"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ พัดวิญญาณดูดกลืนชีวิต",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-038",
    name: "ผู้พิทักษ์สุสานเทพ",
    mapId: "MAP-038",
    level: 69,
    hp: 27600,
    mp: 828,
    atk: 1656,
    def: 828,
    agi: 80,
    style: "Dark",
    goldReward: "3200-5120",
    uniqueDrops: ["เทพเจ้าหอก", "สุสานเทพเกราะ", "เทพผีดิบสร้อยคอ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ หอกเทพเจ้าบรรพกาล",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-039",
    name: "ศิษย์เอกเกาะเซียน",
    mapId: "MAP-039",
    level: 70,
    hp: 28000,
    mp: 840,
    atk: 1680,
    def: 840,
    agi: 88,
    style: "Holy",
    goldReward: "3250-5200",
    uniqueDrops: ["เกาะเซียนกระบี่", "ลอยฟ้าเสื้อคลุม", "เซียนแหวน"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องเกาะ กระบี่เซียนผสมพลังสวรรค์",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-040",
    name: "หัวหน้าโจรมิติ",
    mapId: "MAP-040",
    level: 71,
    hp: 28400,
    mp: 852,
    atk: 1704,
    def: 852,
    agi: 90,
    style: "Dark",
    goldReward: "3300-5280",
    uniqueDrops: ["มิติดาบ", "หุบเขามิติเกราะ", "รอยแยกแหวน"],
    description: "โจรที่ได้รับพลังจากมิติ ใช้รอยแยกมิติโจมตี",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-041",
    name: "ผู้พิทักษ์อาณาจักรเทพมาร",
    mapId: "MAP-041",
    level: 72,
    hp: 28800,
    mp: 864,
    atk: 1728,
    def: 864,
    agi: 86,
    style: "Dark",
    goldReward: "3350-5360",
    uniqueDrops: ["เทพมารโบราณดาบ", "อาณาจักรเทพมารเกราะ", "บรรพกาลตราประทับ"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ พลังเทพมารโบราณ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-042",
    name: "ผู้พิทักษ์สวรรค์ชั้นเก้า",
    mapId: "MAP-042",
    level: 77,
    hp: 30800,
    mp: 924,
    atk: 1848,
    def: 924,
    agi: 92,
    style: "Holy",
    goldReward: "3500-5600",
    uniqueDrops: ["สวรรค์ชั้นเก้าดาบ", "เมฆทองเสื้อคลุม", "เทพเจ้าแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าสวรรค์ แสงสวรรค์ทำลายล้าง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-043",
    name: "ผู้พิทักษ์โลกเซียน",
    mapId: "MAP-043",
    level: 78,
    hp: 31200,
    mp: 936,
    atk: 1872,
    def: 936,
    agi: 95,
    style: "Holy",
    goldReward: "3550-5680",
    uniqueDrops: ["โลกเซียนกระบี่", "ภูเขาเซียนเสื้อคลุม", "อมฤต์จี้"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าโลกเซียน พลังเซียนบริสุทธิ์",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-044",
    name: "ผู้พิทักษ์โลกเทพ",
    mapId: "MAP-044",
    level: 79,
    hp: 31600,
    mp: 948,
    atk: 1896,
    def: 948,
    agi: 98,
    style: "Holy",
    goldReward: "3600-5760",
    uniqueDrops: ["โลกเทพทวน", "เทพโลกเกราะ", "เทพเจ้าแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าโลกเทพ พลังเทพสูงสุด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-045",
    name: "ผู้พิทักษ์ดินแดนบรรพกาล",
    mapId: "MAP-045",
    level: 87,
    hp: 34800,
    mp: 1044,
    atk: 2088,
    def: 1044,
    agi: 100,
    style: "Magic",
    goldReward: "4000-6400",
    uniqueDrops: ["บรรพกาลขวาน", "ดินแดนบรรพกาลเกราะ", "พลังบรรพกาลสร้อยคอ"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าดินแดน พลังบรรพกาลทำลายล้าง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-046",
    name: "ผู้พิทักษ์ชั้นในต้องห้าม",
    mapId: "MAP-046",
    level: 88,
    hp: 35200,
    mp: 1056,
    atk: 2112,
    def: 1056,
    agi: 95,
    style: "Dark",
    goldReward: "4050-6480",
    uniqueDrops: ["ต้องห้ามดาบ", "เขตต้องห้ามเกราะ", "คำสาปตราประทับ"],
    description: "ผู้พิทักษ์ชั้นในที่ถูกสาปให้เป็นอมตะ พลังต้องห้ามร้ายกาจ",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-047",
    name: "ผู้พิทักษ์สุสานเทพ",
    mapId: "MAP-047",
    level: 89,
    hp: 35600,
    mp: 1068,
    atk: 2136,
    def: 1068,
    agi: 100,
    style: "Dark",
    goldReward: "4100-6560",
    uniqueDrops: ["จักรพรรดิเทพหอก", "สุสานจักรพรรดิเกราะ", "เทพผีดิบแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสาปให้เป็นอมตะ หอกจักรพรรดิเทพบรรพกาล",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-048",
    name: "หัวหน้าโจรจักรวาล",
    mapId: "MAP-048",
    level: 90,
    hp: 36000,
    mp: 1080,
    atk: 2160,
    def: 1080,
    agi: 105,
    style: "Magic",
    goldReward: "4150-6640",
    uniqueDrops: ["จักรวาลดาบ", "หุบเขาจักรวาลเกราะ", "ดวงดาวสร้อยคอ"],
    description: "โจรที่ได้รับพลังจากจักรวาล โจมตีด้วยพลังดารา",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-049",
    name: "ศิษย์เอกสำนักมหาเทพ",
    mapId: "MAP-049",
    level: 90,
    hp: 36000,
    mp: 1080,
    atk: 2160,
    def: 1080,
    agi: 108,
    style: "Holy",
    goldReward: "4200-6720",
    uniqueDrops: ["มหาเทพกระบี่", "สำนักมหาเทพเสื้อคลุม", "มหาเทพหยกพก"],
    description: "ศิษย์เอกที่ถูกส่งมาปกป้องสำนัก กระบี่มหาเทพผสมพลังสูงสุด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-050",
    name: "เทพทหารชั้นสูง",
    mapId: "MAP-050",
    level: 90,
    hp: 36000,
    mp: 1080,
    atk: 2160,
    def: 1080,
    agi: 110,
    style: "Holy",
    goldReward: "5000-8000",
    uniqueDrops: ["ประตูสวรรค์ทวน", "เทพทหารเกราะ", "ประตูสวรรค์แหวน"],
    description: "เทพทหารที่ได้รับเลือกจากเทพเจ้า พลังเทพสูงส่ง",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-051",
    name: "ผู้พิทักษ์สวรรค์สูงสุด",
    mapId: "MAP-051",
    level: 90,
    hp: 36000,
    mp: 1080,
    atk: 2160,
    def: 1080,
    agi: 112,
    style: "Holy",
    goldReward: "5100-8160",
    uniqueDrops: ["สวรรค์สูงสุดดาบ", "สวรรค์ชั้นสูงสุดเสื้อคลุม", "เทพเจ้าสูงสุดจี้"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าสวรรค์ชั้นสูงสุด พลังเทพสูงสุด",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  },
  {
    bossId: "MINI-052",
    name: "ผู้พิทักษ์จุดเริ่มต้น",
    mapId: "MAP-052",
    level: 90,
    hp: 36000,
    mp: 1080,
    atk: 2160,
    def: 1080,
    agi: 115,
    style: "Holy",
    goldReward: "5500-8800",
    uniqueDrops: ["จุดเริ่มต้นกระบี่", "จักรวาลเกราะ", "บรรพกาลแหวน"],
    description: "ผู้พิทักษ์ที่ถูกสร้างขึ้นเพื่อเฝ้าจุดเริ่มต้นแห่งจักรวาล",
    reset: "1 ครั้ง/วัน (Daily Reset)"
  }
];

export default miniBossDatabase;